author       = "Jean-François Roy"
baseURL      = "https://devklog.net/"
copyright    = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
languageCode = "en-us"
paginate     = 10
theme        = "hello-friend-ng"
title        = "/dev/klog"

[params]
dateform        = "Jan 2, 2006"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort   = "Jan 2"

# Subtitle for home
homeSubtitle = "One droplet in the rain"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = true

[params.logo]
logoCursorDisabled = true
logoHomeLink       = "/"
logoText           = "/dev/klog"

[[params.social]]
name = "mastodon"
url  = "https://mastodon.gamedev.place/@wavefront"
rel  = "me"
[[params.social]]
name = "github"
url  = "https://github.com/jfroy"
[[params.social]]
name = "strava"
url  = "https://www.strava.com/athletes/1799771"

[[menu.main]]
identifier = "resume"
name       = "Resume"
url        = "/resume"
[[menu.main]]
identifier = "about"
name       = "About"
url        = "/about"

[taxonomies]
category = "blog"
series   = "series"
tag      = "tags"
